### PR TITLE
Issue 21

### PR DESCRIPTION
**Pull request by rkass**
Necessitate the presence of `awsconfiglocation` AND `awsprofile` for the usage of `ProfilesCredentialsProvider`

### CODE REVIEW

**Comment by danielwillgeorge** [comment]
This lookin' good to me...just curious: why the adjustment?

**Comment by danielwillgeorge** [comment]
@rkass ^

**Comment by rkass** [comment]
@danielwillgeorge see https://github.com/disneystreaming/pg2k4j/issues/21

**Comment by danielwillgeorge** [comment]
nice thanks @rkass

**Pull request merged**
